# Window Stuff
WIDTH = 800
HEIGHT = 600
EDGE_GAP = 70

# Boid Stuff
BOID_COUNT = 100
VIS_RANGE = 100
PROTECT_RANGE = 50
MAX_SPEED = 5
ALIGNMENT_FACTOR = 0.05
COHESION_FACTOR = 0.0002
SEPARATION_FACTOR = 0.09

# Player Interaction

# Triangle
PLAYER_ATTRACT = 0
PLAYER_X = 0
PLAYER_Y = 0
PLAYER_COHESION = 20
PLAYER_SEPARATION = 5

# Mouse
MOUSE_ATTRACT = -1
MOUSE_COHESION = 20
MOUSE_SEPARATION = 5